name: Docker Build and Push

on:
  push:
    branches:
      - dev-01  # Replace with your branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./lesson-cicd/practice-04  # Path to the Dockerfile and build context
          push: true
          tags: |
            dinghy123/app-node:${{ github.sha }}

      - name: Logout from Docker Hub
        run: docker logout
